spring.datasource.url=jdbc:postgresql://localhost:5432/easycon
spring.datasource.username=tribosoftec
spring.datasource.password=123456789

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

cors.allowed-origins=http://localhost:3000
cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
cors.allowed-headers=Content-Type,Authorization
cors.allow-credentials=true

JWT_SECRET=x6KWKxmlRKPgX9awX7mt3nssi7O3ezk1BEMs3jF56Yc

spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:tribosoftec@gmail.com}
spring.mail.password=${MAIL_PASSWORD:jgke hoqr rfnx soyg}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
